version: 2.1

workflows:
    test-env-vars:
      jobs:
        - build:
            context: gitlab-dependabot # has an env var called MY_ENV_VAR
  
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-alpine
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t CircleCI-Public/circleci-demo-docker:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push CircleCI-Public/circleci-demo-docker:$TAG